### ISSUE TITLE
Input required and not supplied: token

### ISSUE THREAD

**Issue by superdeen** [DK9510/automate-with-actions#1]
I get the error shown
![Uploading Screenshot_20230308-153707_Chrome.jpg…]()
 in the screenshots attached when I run the workflow

**Comment by DK9510** [comment]
@superdeen actually i can not see your screen shot , can you re upload it, the link will redirect to this page.

**Comment by superdeen** [comment]
![Uploading Screenshot_20230308-153628_Chrome.jpg…]()

**Comment by superdeen** [comment]
Run actions/checkout@v2
  with:
    repository: Github-Username/automate-with-actions
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
    set-safe-directory: true
Error: Input required and not supplied: token

The screenshot seems to be broken. The error message is shown above.

**Comment by DK9510** [comment]
have you configured your github access token with your repository, which you have downloaded and re initialized, i guess error telling that access token is required but not supplied, have you read the README.md cause i have explain all things, how to set up etc.

**Comment by superdeen** [comment]
Thanks. I would read the README.md file carefully again, it seems I had not set action secret
